### ISSUE TITLE
EADDRINUSE when changes made on server

### ISSUE THREAD

**Issue by edwinthinks** [edwinthinks/pern-stack-boilerplate#10]
This occurs when changes are made the user-controller. The server still seems to work but logs have halted.

```
7:07:07 AM api.1 |  [nodemon] restarting due to changes...
7:07:08 AM api.1 |  [nodemon] starting `node -r esm index.js`
7:07:10 AM api.1 |  Error: listen EADDRINUSE: address already in use :::3001
7:07:10 AM api.1 |      at Server.setupListenHandle [as _listen2] (net.js:1270:14)
7:07:10 AM api.1 |      at listenInCluster (net.js:1318:12)
7:07:10 AM api.1 |      at Server.listen (net.js:1405:7)
7:07:10 AM api.1 |      at Function.listen (/Users/edwinmak/projects/pern-stack-boilerplate/server/node_modules/express/lib/application.js:618:24)
7:07:10 AM api.1 |      at resolve (/Users/edwinmak/projects/pern-stack-boilerplate/server/src/start.js:24:24)
7:07:10 AM api.1 |      at new Promise (<anonymous>)
7:07:10 AM api.1 |      at startServer (/Users/edwinmak/projects/pern-stack-boilerplate/server/src/start.js:23:10)
7:07:10 AM api.1 |      at Object.<anonymous> (/Users/edwinmak/projects/pern-stack-boilerplate/server/index.js:24:1)
7:07:10 AM api.1 |      at Generator.next (<anonymous>)
```

**Comment by edwinthinks** [comment]
This might be caused by the server trying to restart before the server can close. Adding a `delay` in the nodemon config can work - https://github.com/remy/nodemon#packagejson
